<?php

/**
 * @file
 * Provides a movie entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\taxonomy\Entity\Vocabulary;
use \Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_theme().
 */
function movie_theme() {
  return [
    'movie' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_install().
 */
function movie_install() {
  $vocabulary = Vocabulary::create([
    'vid' => 'genre',
    'name' => 'Genre',
  ]);
  $vocabulary->save();

  $terms = [
    [
      'name' => 'Comedy',
      'vid' => 'genre',
    ],
    [
      'name' => 'Drama',
      'vid' => 'genre',
    ],
    [
      'name' => 'Action',
      'vid' => 'genre',
    ],
  ];

  foreach ($terms as $term) {
    $term = Term::create($term);
    $term->save();
  }

}

/**
 * Implements hook_uninstall().
 */
function movie_uninstall() {
  $vocabulary = Vocabulary::load('genre');
  $vocabulary->delete();
}

/**
 * Prepares variables for movie templates.
 *
 * Default template: movie.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the movie information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_movie(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

